In [1]:
from utils import *
from create_flop_data import FlopDataset, flop_collate_fn
import torch
from torchvision import transforms
from torch.utils.data import DataLoader

In [2]:
data = FlopDataset()

In [7]:
import pandas as pd

In [ ]:
data_pandas = pd.DataFrame({
    'flop': data.FLOPS,
    'suitedness': data.suitedness,
    'pairness': data.pairness,
    'connectedness': data.connectedness,
    'high_low_texture': data.high_low_texture,
    'high_card': data.high_card,
    'straightness': data.straightness
})
data_pandas.to_csv('flop_data.csv')

In [ ]:
data.FLOPS #= list(combinations(DECK, 3))
        


[('2s', '2h', '2c'),
 ('2s', '2h', '2d'),
 ('2s', '2h', '3s'),
 ('2s', '2h', '3h'),
 ('2s', '2h', '3c'),
 ('2s', '2h', '3d'),
 ('2s', '2h', '4s'),
 ('2s', '2h', '4h'),
 ('2s', '2h', '4c'),
 ('2s', '2h', '4d'),
 ('2s', '2h', '5s'),
 ('2s', '2h', '5h'),
 ('2s', '2h', '5c'),
 ('2s', '2h', '5d'),
 ('2s', '2h', '6s'),
 ('2s', '2h', '6h'),
 ('2s', '2h', '6c'),
 ('2s', '2h', '6d'),
 ('2s', '2h', '7s'),
 ('2s', '2h', '7h'),
 ('2s', '2h', '7c'),
 ('2s', '2h', '7d'),
 ('2s', '2h', '8s'),
 ('2s', '2h', '8h'),
 ('2s', '2h', '8c'),
 ('2s', '2h', '8d'),
 ('2s', '2h', '9s'),
 ('2s', '2h', '9h'),
 ('2s', '2h', '9c'),
 ('2s', '2h', '9d'),
 ('2s', '2h', 'Ts'),
 ('2s', '2h', 'Th'),
 ('2s', '2h', 'Tc'),
 ('2s', '2h', 'Td'),
 ('2s', '2h', 'Js'),
 ('2s', '2h', 'Jh'),
 ('2s', '2h', 'Jc'),
 ('2s', '2h', 'Jd'),
 ('2s', '2h', 'Qs'),
 ('2s', '2h', 'Qh'),
 ('2s', '2h', 'Qc'),
 ('2s', '2h', 'Qd'),
 ('2s', '2h', 'Ks'),
 ('2s', '2h', 'Kh'),
 ('2s', '2h', 'Kc'),
 ('2s', '2h', 'Kd'),
 ('2s', '2h', 'As'),
 ('2s', '2h',

In [3]:
trainloader = DataLoader(data, batch_size=5, shuffle=True, collate_fn=flop_collate_fn)

In [5]:
SUITS_DICT

{'s': 0, 'h': 1, 'c': 2, 'd': 3}

In [4]:
next(iter(trainloader))

(tensor([[ 5.,  1.,  0.,  0.,  0.,  5.,  0.,  0.,  0.,  1.,  8.,  0.,  0.,  1.,
           0.],
         [ 3.,  0.,  0.,  0.,  1.,  6.,  1.,  0.,  0.,  0., 11.,  1.,  0.,  0.,
           0.],
         [ 8.,  0.,  0.,  1.,  0., 11.,  0.,  0.,  0.,  1., 13.,  0.,  0.,  1.,
           0.],
         [ 3.,  1.,  0.,  0.,  0., 10.,  0.,  1.,  0.,  0., 10.,  0.,  0.,  0.,
           1.],
         [ 3.,  0.,  0.,  0.,  1., 13.,  1.,  0.,  0.,  0., 14.,  1.,  0.,  0.,
           0.]]),
 [('5s', '5d', '8c'),
  ('3d', '6s', 'Js'),
  ('8c', 'Jd', 'Kc'),
  ('3s', 'Th', 'Td'),
  ('3d', 'Ks', 'As')],
 tensor([0., 1., 1., 0., 1.]),
 tensor([1., 0., 0., 2., 0.]),
 tensor([0., 0., 0., 0., 1.]),
 tensor([0., 0., 2., 2., 2.]),
 tensor([ 6.,  9., 11.,  8., 12.]),
 tensor([0., 0., 0., 0., 0.]))