In [1]:
import pandas as pd
import numpy as np
from create_flop_data import FlopDataset, flop_collate_fn
import torch
from torchvision import transforms
from torch.utils.data import DataLoader
import torch.nn as nn

In [2]:
df = pd.read_parquet('flopdata.parquet')

In [3]:
data = FlopDataset(data=df)

In [7]:
trainloader = DataLoader(data, batch_size=3, shuffle=True, collate_fn=flop_collate_fn)

In [8]:
next(iter(trainloader))

(tensor([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
          0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
          0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.],
         [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
          0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.]],
        dtype=torch.float64),
 [array(['5s', '7h', 'Ts'], dtype=object),
  array(['4c', '4d', 'Ad'], dtype=object),
  array(['6c', '9c', 'Jh'], dtype=object)],
 tensor([1., 1., 1.]),
 tensor([0., 1., 0.]),
 tensor([0., 0., 0.]),
 tensor([0., 0., 1.]),
 tensor([ 8., 12.,  9.]),
 tensor([0., 0.,